version: '3.3'

services:
  sample:
    build:
      context: .
      dockerfile: ./Dockerfile
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=123
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=dynamodb
    ports:
      - '4566:4566'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./script-file:/docker-entrypoint-initaws.d"
      - "./user-table.json:/user-table.json"
