package br.com.spring.dynamodb.model.entity

import br.com.spring.dynamodb.constants.TABLE_NAME
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.fasterxml.jackson.annotation.JsonInclude
import java.io.Serializable

@JsonInclude(JsonInclude.Include.NON_NULL)
@DynamoDBDocument
@DynamoDBTable(tableName = TABLE_NAME)
class User(

    @get:DynamoDBRangeKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    var userId: String? = null,

    @get:DynamoDBHashKey(attributeName = "document")
    var document: String? = null,

    @DynamoDBAttribute(attributeName = "userName")
    var name: String? = null,

    @DynamoDBAttribute(attributeName = "lastName")
    var lastName: String? = null,

    @DynamoDBAttribute(attributeName = "birthDate")
    var birthDate: String? = null,

    @DynamoDBAttribute(attributeName = "nickName")
    var nickName: String? = null,

    @DynamoDBAttribute(attributeName = "country")
    var country: String? = null,

) : Serializable
