server:
  port: ${ENV_PORT}
  servlet:
    contextPath: ${ENV_CTX_PATH}

spring:
  profiles:
    active: ${ENV}
  config:
    use-legacy-processing: true
  application:
    name: spring-with-dynamodb
  zipkin:
    base-url: ${ENV_ZIPKIN_HOST}
    enabled: ${ENV_ZIPKIN_ENABLE}
  sleuth:
    enabled: ${ENV_SLEUTH_ENABLE}

aws:
  dynamo:
    endpoint: ${ENV_DYNAMO_DB_HOST:localhost:4566}
  accesskey: ${ENV_AWS_ACCESS_KEY}
  secretkey: ${ENV_AWS_SECRET_KEY}
  region: ${ENV_AWS_REGION}